/**
 * Emit a typed ABI from the compiled artifact.
 * Generated rather than hand-copied so it cannot drift from the contract.
 * Run via `npm run gen:abi` after any contract change.
 */
import { readFileSync, writeFileSync } from "node:fs";

const artifact = JSON.parse(
  readFileSync("artifacts/contracts/ExitBadge.sol/ExitBadge.json", "utf8"),
);

const wanted = new Set([
  "mint", "tokenURI", "badgeOf", "totalMinted", "ownerOf", "balanceOf",
  "name", "symbol", "owner", "BadgeMinted",
  "IllegalCharacter", "FieldTooLong", "ImageTooLarge", "ImageEmpty",
  "InvalidRecipient", "UnknownMime", "NonexistentToken",
]);

const abi = artifact.abi.filter(
  (e: { type: string; name?: string }) => e.type === "constructor" || (e.name && wanted.has(e.name)),
);

writeFileSync(
  "lib/abi.ts",
  `// GENERATED by scripts/gen-abi.ts — do not edit by hand.
// Regenerate with: npm run gen:abi
export const EXIT_BADGE_ABI = ${JSON.stringify(abi, null, 2)} as const;
`,
);
console.log(`wrote lib/abi.ts with ${abi.length} entries`);
